-- database/migrations/V000__setup_entornos_negocio.sql
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = FREEPDB1;
-- Entorno 1: Academia
CREATE TABLESPACE TBS_ACADEMIA DATAFILE 'academia01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;
CREATE USER admin_academia IDENTIFIED BY "Academia_2026_*"
 DEFAULT TABLESPACE TBS_ACADEMIA QUOTA UNLIMITED ON TBS_ACADEMIA;
GRANT DB_DEVELOPER_ROLE, CREATE SESSION TO admin_academia;
-- Entorno 2: Clinica
CREATE TABLESPACE TBS_CLINICA DATAFILE 'clinica01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;
CREATE USER admin_clinica IDENTIFIED BY "Clinica_2026_*"
 DEFAULT TABLESPACE TBS_CLINICA QUOTA UNLIMITED ON TBS_CLINICA;
GRANT DB_DEVELOPER_ROLE, CREATE SESSION TO admin_clinica;
-- Entorno 3: Retail
CREATE TABLESPACE TBS_RETAIL DATAFILE 'retail01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;
CREATE USER admin_retail IDENTIFIED BY "Retail_2026_*"DEFAULT TABLESPACE TBS_RETAIL QUOTA UNLIMITED ON TBS_RETAIL;
GRANT DB_DEVELOPER_ROLE, CREATE SESSION TO admin_retail;
-- Entorno 4: Logistica
CREATE TABLESPACE TBS_LOGISTICA DATAFILE 'logistica01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;
CREATE USER admin_logistica IDENTIFIED BY "Logistica_2026_*"
 DEFAULT TABLESPACE TBS_LOGISTICA QUOTA UNLIMITED ON TBS_LOGISTICA;
GRANT DB_DEVELOPER_ROLE, CREATE SESSION TO admin_logistica;
-- Entorno 5: Fintech
CREATE TABLESPACE TBS_FINTECH DATAFILE 'fintech01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;
CREATE USER admin_fintech IDENTIFIED BY "Fintech_2026_*"
 DEFAULT TABLESPACE TBS_FINTECH QUOTA UNLIMITED ON TBS_FINTECH;
GRANT DB_DEVELOPER_ROLE, CREATE SESSION TO admin_fintech;
PROMPT == Verificacion: usuarios de negocio ==
SELECT username, default_tablespace, account_status FROM dba_users
WHERE username LIKE 'ADMIN\_%' ESCAPE '\' ORDER BY username;
EXIT
